use SuperStore_3A

select * from Branches
select * from Customers
select * from Categories
select * from Order_Details_bak

--1. Branch Performance

--1.Can you write a query to show total sales and total orders per branch?
SELECT B.REGION AS BRANCH_REGION,B.CITY AS BRANCH_CITY,SUM(O.TOTALBASKET) AS TOTAL_SALES,COUNT(O.ORDERID) AS TOTAL_ORDERS
FROM BRANCHES B LEFT JOIN Orders_bak O ON B.BRANCH_ID = O.BRANCH_ID GROUP BY B.BRANCH_ID,B.REGION,B.CITY ORDER BY TOTAL_SALES DESC;

--2.I’d like to know which branch has the highest revenue — can you retrieve the top 3 branches by sales amount?

SELECT TOP 3 B.BRANCH_ID, B.REGION AS BRANCH_REGION, B.CITY AS BRANCH_CITY 
, SUM(O.TOTALBASKET) AS TOTALSALE, COUNT(O.ORDERID) AS TOTAL_ORDER
FROM BRANCHES B LEFT JOIN Orders_bak O ON B.BRANCH_ID =  O.BRANCH_ID 
GROUP BY B.BRANCH_ID, B.REGION, B.CITY
ORDER BY TOTALSALE DESC

--3. Can you calculate the average order value for each branch?
SELECT B.BRANCH_ID, B.REGION AS BRANCH_REGION, B.CITY AS BRANCH_CITY 
, CAST(AVG(O.TOTALBASKET) AS DECIMAL(10,2)) AS AVG_SALE
FROM BRANCHES B LEFT JOIN Orders_bak O ON B.BRANCH_ID =  O.BRANCH_ID 
GROUP BY B.BRANCH_ID, B.REGION, B.CITY
ORDER BY AVG_SALE DESC

--4.	I’m curious which branch has the most unique customers — can you show that?
SELECT TOP 1 B.BRANCH_ID, B.REGION AS BRANCH_REGION, B.CITY AS BRANCH_CITY
,COUNT(DISTINCT USERID) AS UNIQUE_CUSTOMER_COUNT
FROM BRANCHES B LEFT JOIN Orders_bak O ON B.BRANCH_ID =  O.BRANCH_ID 
GROUP BY B.BRANCH_ID, B.REGION , B.CITY 
ORDER BY UNIQUE_CUSTOMER_COUNT DESC

--2. Sales & Revenue Insights

--5.Can you write a query to calculate monthly or quarterly revenue trends?
--MONTHLY
SELECT DATENAME(MONTH,ORDER_DATE) AS MONTH,ROUND(SUM(TOTALBASKET),2) AS REVENUE FROM Orders_bak
GROUP BY DATENAME(MONTH,ORDER_DATE),DATEPART(MONTH,ORDER_DATE)
ORDER BY DATEPART(MONTH,ORDER_DATE)

--QUATERLY
SELECT CONCAT('QUATER ',DATENAME(QUARTER,ORDER_DATE)) AS QUARTER,ROUND(SUM(TOTALBASKET),2) AS REVENUE FROM Orders_bak
GROUP BY CONCAT('QUATER ',DATENAME(QUARTER,ORDER_DATE)),DATEPART(QUARTER,ORDER_DATE)
ORDER BY DATEPART(QUARTER,ORDER_DATE)

--6.	Can you identify the highest-selling products (by quantity or revenue)?
--BY TOTAL REVENUE
SELECT  TOP 1 C.PRODUCT_NAME,SUM(OD.TOTALPRICE) AS TOTAL_REVENUE FROM Order_Details_bak  OD
INNER JOIN Categories C ON OD.ITEMID = C.ITEMID
INNER JOIN Orders_bak O ON OD.ORDERID = O.ORDERID
GROUP BY C.PRODUCT_NAME
ORDER BY TOTAL_REVENUE DESC

--QUATERLY TOP SELLING PRODUCT
WITH PRODUCT_DETAIL AS(
SELECT  C.PRODUCT_NAME,CONCAT('QUATER ',DATENAME(QUARTER,ORDER_DATE)) AS QUARTER
,SUM(OD.TOTALPRICE) AS TOTAL_REVENUE ,
DENSE_RANK()OVER(PARTITION BY CONCAT('QUATER ',DATENAME(QUARTER,ORDER_DATE)) ORDER BY SUM(OD.TOTALPRICE) DESC) RANK_NUM
FROM Order_Details_bak OD
INNER JOIN Categories C ON OD.ITEMID = C.ITEMID
INNER JOIN Orders_bak O ON OD.ORDERID = O.ORDERID
GROUP BY C.PRODUCT_NAME,CONCAT('QUATER ',DATENAME(QUARTER,ORDER_DATE)))

SELECT * FROM PRODUCT_DETAIL WHERE RANK_NUM = 1;


--BY QUANTITY 
SELECT  TOP 1 C.PRODUCT_NAME,SUM(OD.Quantity) AS TOTAL_QUANTITY FROM Order_Details_bak OD
INNER JOIN Categories C ON OD.ITEMID = C.ITEMID
INNER JOIN Orders_bak O ON OD.ORDERID = O.ORDERID
GROUP BY C.PRODUCT_NAME
ORDER BY TOTAL_QUANTITY DESC

--7.	Can you find which day of the week generates the most sales overall?
SELECT DATENAME(WEEKDAY,ORDER_DATE) AS WEEKDAYS, ROUND(SUM(TOTALBASKET),2) AS TOTAL_SALES FROM Orders_bak
GROUP BY DATENAME(WEEKDAY,ORDER_DATE), DATEPART(WEEKDAY,ORDER_DATE)
ORDER BY DATEPART(WEEKDAY,ORDER_DATE)

--IN WHICH DAYS WE HAVE HIGHEST SALES

SELECT TOP 1 DATENAME(WEEKDAY,ORDER_DATE) AS WEEKDAYS, ROUND(SUM(TOTALBASKET),2) AS TOTAL_SALES FROM Orders_bak
GROUP BY DATENAME(WEEKDAY,ORDER_DATE)
ORDER BY TOTAL_SALES DESC

--MONTHLY WHICH DAY WE HAVE HIGHEST SALES

SELECT MONTH,WEEKDAYS,TOTAL_SALES FROM (
SELECT DATENAME(MONTH,ORDER_DATE) AS MONTH,DATEPART(MONTH,ORDER_DATE)AS MONTHNUMBER,
DATENAME(WEEKDAY,ORDER_DATE) AS WEEKDAYS, 
ROUND(SUM(TOTALBASKET),2) AS TOTAL_SALES ,
DENSE_RANK()OVER(PARTITION BY DATENAME(MONTH,ORDER_DATE) ORDER BY ROUND(SUM(TOTALBASKET),2) DESC) RANK_NUM
FROM Orders_bak
GROUP BY DATENAME(MONTH,ORDER_DATE) ,DATEPART(MONTH,ORDER_DATE), DATENAME(WEEKDAY,ORDER_DATE)
)T
WHERE RANK_NUM = 1
ORDER BY MONTHNUMBER

--MONTHLY WHICH WeekOfMonth WE HAVE HIGHEST SALES
--(DATEPART(WEEK, OrderDate) - DATEPART(WEEK, DATEADD(DAY, 1 - DAY(OrderDate), OrderDate)) + 1)

with cte as(
SELECT  DATENAME(MONTH,ORDER_DATE) AS MONTH,DATEPART(MONTH,ORDER_DATE)AS MONTHNUMBER,
CONCAT('WEEK ',(DATEPART(WEEK, ORDER_DATE) - DATEPART(WEEK, DATEADD(DAY, 1 - DAY(ORDER_DATE), ORDER_DATE)) + 1)) AS WEEKOFMONTH
, SUM(TOTALBASKET) AS TOTALSALE
FROM Orders_bak
GROUP BY DATENAME(MONTH,ORDER_DATE) ,DATEPART(MONTH,ORDER_DATE),
CONCAT('WEEK ',(DATEPART(WEEK, ORDER_DATE) - DATEPART(WEEK, DATEADD(DAY, 1 - DAY(ORDER_DATE), ORDER_DATE)) + 1))),
cte2 as(
select *, DENSE_RANK()over(partition by month order by totalsale desc) rank from cte)
select month, WEEKOFMONTH,TOTALSALE from cte2 where rank = 1
order by MONTHNUMBER

--3. Product & Category Analysis

--8 Can you create a query that shows sales by product category?
select C.PRODUCT_CATEGORY,SUM(OD.TOTALPRICE) AS TOTALSALE from Order_Details_bak od
INNER JOIN Categories C ON OD.ITEMID = C.ITEMID
GROUP BY C.PRODUCT_CATEGORY

--9.I want to see which categories perform best in each branch — can you group and rank them?

SELECT B.BRANCH_ID,B.REGION AS BRANCH_REGION,C.PRODUCT_CATEGORY,SUM(OD.TOTALPRICE) AS TOTALSALE 
,DENSE_RANK()OVER(PARTITION BY B.BRANCH_ID,B.REGION ORDER BY SUM(OD.TOTALPRICE) DESC) RANKS
FROM Orders_bak O
INNER JOIN Order_Details_bak OD ON O.ORDERID = OD.ORDERID
INNER JOIN Categories C ON OD.ITEMID = C.ITEMID
INNER JOIN Branches B ON O.BRANCH_ID = B.BRANCH_ID
GROUP BY B.BRANCH_ID,B.REGION ,C.PRODUCT_CATEGORY;

--I want to see which categories perform best in each branch

WITH SALEDATA AS(
SELECT B.BRANCH_ID,B.REGION AS BRANCH_REGION,C.PRODUCT_CATEGORY,SUM(OD.TOTALPRICE) AS TOTALSALE 
,DENSE_RANK()OVER(PARTITION BY B.BRANCH_ID,B.REGION ORDER BY SUM(OD.TOTALPRICE) DESC) RANKS
FROM Orders_bak O
INNER JOIN Order_Details_bak OD ON O.ORDERID = OD.ORDERID
INNER JOIN Categories C ON OD.ITEMID = C.ITEMID
INNER JOIN Branches B ON O.BRANCH_ID = B.BRANCH_ID
GROUP BY B.BRANCH_ID,B.REGION ,C.PRODUCT_CATEGORY)
SELECT * FROM SALEDATA WHERE RANKS = 1

--OR (SUBQUERY)

SELECT * FROM (SELECT B.BRANCH_ID,B.REGION AS BRANCH_REGION,C.PRODUCT_CATEGORY,SUM(OD.TOTALPRICE) AS TOTALSALE 
,DENSE_RANK()OVER(PARTITION BY B.BRANCH_ID,B.REGION ORDER BY SUM(OD.TOTALPRICE) DESC) RANKS
FROM Orders_bak O
INNER JOIN Order_Details_bak OD ON O.ORDERID = OD.ORDERID
INNER JOIN Categories C ON OD.ITEMID = C.ITEMID
INNER JOIN Branches B ON O.BRANCH_ID = B.BRANCH_ID
GROUP BY B.BRANCH_ID,B.REGION ,C.PRODUCT_CATEGORY) AS T
WHERE RANKS = 1

--10.Can you identify the top 5 products contributing most to revenue?

select TOP 5 C.PRODUCT_NAME,SUM(OD.TOTALPRICE) AS TOTALSALE from Order_Details_bak od
INNER JOIN Categories C ON OD.ITEMID = C.ITEMID
GROUP BY C.PRODUCT_NAME
ORDER BY TOTALSALE DESC


--OR(TOP 5 WITH RANKING)

SELECT * FROM (
select  C.PRODUCT_NAME,SUM(OD.TOTALPRICE) AS TOTALSALE 
,DENSE_RANK()OVER (ORDER BY SUM(OD.TOTALPRICE ) DESC) RANKS
from Order_Details_bak od
INNER JOIN Categories C ON OD.ITEMID = C.ITEMID
GROUP BY C.PRODUCT_NAME ) AS t
WHERE RANKS  <= 5

--4. Customer Insights

--11.Can you show the top 10 customers based on total purchase amount?


SELECT * FROM (
SELECT C.USERID,C.NAMESURNAME AS USERNAME, SUM(O.TOTALBASKET) AS TOTAL_PURCHASE
,DENSE_RANK() OVER(ORDER BY SUM(O.TOTALBASKET) DESC) AS RANKS
FROM Orders_bak O
INNER JOIN Customers C ON O.USERID =C.USERID
GROUP BY C.USERID,C.NAMESURNAME ) AS T
WHERE RANKS <= 10

--12.Can you calculate the average number of orders per customer?

SELECT CAST((COUNT(ORDERID)*1.0)/COUNT(DISTINCT USERID)AS DECIMAL(15,2)) AS AVG_ORDER_PER_CUSTOMER
FROM Orders_bak O


--13.I’d like to know which customers haven’t ordered recently — can you query customers who haven’t placed an order in the last 3 months?

SELECT MAX(ORDER_DATE) FROM Orders_bak  --2023-05-14 00:00:00.000 TO 2023-08-14 00:00:00.000

DECLARE @MAXDATE DATE
SET @MAXDATE = (SELECT MAX(ORDER_DATE) FROM Orders_bak )

SELECT * FROM Customers WHERE USERID NOT IN (
SELECT USERID FROM Orders_bak 
WHERE ORDER_DATE BETWEEN DATEADD(MONTH,-3,@MAXDATE) AND @MAXDATE)

--OR

SELECT * FROM Customers WHERE USERID NOT IN (
SELECT USERID FROM Orders_bak 
WHERE ORDER_DATE BETWEEN DATEADD(MONTH,-3,(SELECT MAX(ORDER_DATE) FROM Orders_bak)) 
AND (SELECT MAX(ORDER_DATE) FROM Orders_bak))

--5. Order & Transaction Patterns

--14.Can you find orders that have abnormally high quantities or total prices?
SELECT * FROM Orders_bak WHERE TOTALBASKET > (SELECT AVG(TOTALBASKET) + 2 * STDEV(TOTALBASKET)FROM Orders_bak);

--15.Can you group orders by payment method or order status (if fields exist) and show totals?

SELECT C.STATUS_ AS Customer_Status,COUNT(O.ORDERID) AS Total_Orders,SUM(O.TOTALBASKET) AS Total_Amount
FROM Orders_bak O JOIN Customers C ON O.USERID = C.USERID GROUP BY C.STATUS_;

--6. Advanced/Analytical Queries

--16.Can you use window functions to calculate a running total of sales by date?

SELECT ORDER_DATE,SUM(TOTALBASKET) AS Daily_Sales,SUM(SUM(TOTALBASKET))
OVER (ORDER BY ORDER_DATE ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS Running_Total
FROM Orders_bak GROUP BY ORDER_DATE ORDER BY ORDER_DATE;


--17.Can you rank products within each category by total revenue using RANK() or DENSE_RANK()?

WITH ProductRevenue AS (SELECT C.PRODUCT_CATEGORY,C.PRODUCT_NAME,SUM(OD.TOTALPRICE) AS Total_Revenue FROM dbo.Order_Details_bak OD
JOIN dbo.Categories C ON OD.ITEMID = C.ITEMID GROUP BY C.PRODUCT_CATEGORY, C.PRODUCT_NAME)
SELECT PRODUCT_CATEGORY,PRODUCT_NAME,Total_Revenue,DENSE_RANK() OVER (PARTITION BY PRODUCT_CATEGORY ORDER BY Total_Revenue DESC) AS Revenue_Rank
FROM ProductRevenue ORDER BY PRODUCT_CATEGORY, Revenue_Rank;

--18.Can you write a query to find the percentage contribution of each branch to total company sales?

SELECT BRANCH_ID,SUM(TOTALBASKET) AS Branch_Sales,SUM(TOTALBASKET) * 100.0 / SUM(SUM(TOTALBASKET)) OVER () AS Sales_Percentage
FROM Orders_bak GROUP BY BRANCH_ID ORDER BY Sales_Percentage DESC;








































